# Constant

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.14.0'

In [3]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [4]:
a=tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [5]:
a=tf.constant(10.32)
a

<tf.Tensor: shape=(), dtype=float32, numpy=10.32>

In [6]:
c=tf.constant("Hamza")
c

<tf.Tensor: shape=(), dtype=string, numpy=b'Hamza'>

In [7]:
d=tf.constant(True)
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# Variable

In [8]:
tf.Variable(10)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [10]:
a = tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [11]:
a.name

'Variable:0'

In [12]:
a.shape

TensorShape([4])

In [13]:
a.dtype

tf.int32

In [14]:
a.numpy()

array([1, 2, 3, 4])

In [15]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

# create tf using integer ,float , string, bool , complex number

In [16]:
t_f = tf.Variable([1.2,4.4,5,6])
t_f

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.2, 4.4, 5. , 6. ], dtype=float32)>

In [17]:
t_s =tf.Variable(['a','b','c','d'])
t_s

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'a', b'b', b'c', b'd'], dtype=object)>

In [18]:
t_b = tf.Variable([True,False])
t_b

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [19]:
t_cx =tf.Variable([3 + 4j])
t_cx

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+4.j])>

# Create TF from Constant Tensorflow Variable

In [20]:
t_con =tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [21]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

# Create TF Variable with Different shape

In [22]:
t_2d = tf.Variable([[1,2],[3,4]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [23]:
t_2d = tf.Variable([[1,2],[3,4]], shape=(2, 2), dtype='float')
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [24]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [25]:
tf.reshape(a, (2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

# Get Index of Highest Value

In [26]:
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [27]:
tf.argmax(t_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1], dtype=int64)>

In [28]:
import numpy as np

In [29]:
tf.argmax(t_2d).numpy()

array([1, 1], dtype=int64)

# Viewed/Convert as a tensor

In [30]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [31]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [32]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

# Change/Assign new value to tensor

In [33]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [34]:
a.assign([4,5,6,7])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 7])>

In [35]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 7])>

# Assign variable with another memory

In [36]:
a.assign_add([8,9,11,12])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([12, 14, 17, 19])>