
# Sparce Tensor


In [1]:
import tensorflow as tf

In [2]:
st1 = tf.sparse.SparseTensor(indices=[[0,2],[3,4]],values=[10,20], dense_shape=[3,10])
st1

SparseTensor(indices=tf.Tensor(
[[0 2]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

In [3]:
import tensorflow as tf

# create a sparse tensor
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])

# convert it to a dense tensor
dense_tensor = tf.sparse.to_dense(sparse_tensor)

# run the tensor
print(dense_tensor)

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


# create sparce tensor from dense

In [4]:
import numpy as np

In [5]:
np_array = np.array([[1,0,0,0],
                    [0,0,0,0],
                    [0,0,2,0],
                    [0,0,0,4]])
np_array

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

In [6]:
import tensorflow as tf

# Check the TensorFlow version
print(tf.__version__)

# Import the sparse module
from tensorflow.sparse import SparseTensor

2.14.0


In [7]:
#from tensorflow import sparse

In [8]:
st2_fd = tf.sparse.from_dense(np_array)


In [9]:
print(st2_fd)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 4], shape=(3,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))


# Extract the value, indices and shape of sparse tensor

In [10]:
st2_fd.values

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 4])>

In [11]:
st2_fd.values.numpy()

array([1, 2, 4])

In [12]:
st2_fd.values.numpy().tolist()

[1, 2, 4]

In [14]:
st2_fd.indices.numpy().tolist()

[[0, 0], [2, 2], [3, 3]]

In [15]:
st2_fd.shape

TensorShape([4, 4])

# Sparse tensor to dense

if most of the element are nonzero , then tensor is considered dense

In [16]:
dt_fst = tf.sparse.to_dense(st2_fd)
dt_fst

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])>

# conver dense tensor into numpy array

In [18]:
dt_fst.numpy()

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

# Mathemicatical operation on the sparse tensor

In [19]:
st_add = tf.sparse.add(st2_fd, st2_fd)
st_add

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2 4 8], shape=(3,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

In [20]:
tf.sparse.to_dense(st_add)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[2, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 8]])>